FROM alpine:latest

# Install only what the user actually needs (bash)
RUN apk add --no-cache bash

# --- Setup for the user ---
RUN adduser -D -s /bin/bash level13 && \
    echo "level13:FvY2xYp9monYNxsmbKMozV5" | chpasswd

# Set the working directory for the level13 user
WORKDIR /home/level13

# Create the get_password script with the hidden flag
RUN echo '#!/bin/bash\necho "WfjrA4M9sXDBvZnw"' > get_password && \
    chown level13:level13 get_password && \
    chmod 000 get_password

# ^ chmod 400 → read-only for owner.
# This prevents execution at first.
# Player must run: chmod u+x get_password
# Then execute: ./get_password → flag

# Switch to the user for the interactive session
USER level13

CMD ["/bin/bash", "-c", "tail -f /dev/null"]
